name: Validate Gradle Wrapper
on: [push, pull_request]
permissions: read-all

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            downloads.gradle.org:443
            downloads.gradle-dn.com:443
            github.com:443
            services.gradle.org:443
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0
